apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: composable-resource-operator-system
type: Opaque
stringData:
  username: {{ quote $.Values.global.fti_cdi.credentials.username }}
  password: {{ quote $.Values.global.fti_cdi.credentials.password }}
  client_id: {{ quote $.Values.global.fti_cdi.credentials.client_id }}
  client_secret: {{ quote $.Values.global.fti_cdi.credentials.client_secret }}
  realm: {{ quote $.Values.global.fti_cdi.credentials.realm }}
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-cert
  namespace: composable-resource-operator-system
type: kubernetes.io/tls
stringData:
  tls.crt: |
{{- nindent 4 .Values.common.webhook.server.crt }}
  tls.key: |
{{- nindent 4 .Values.common.webhook.server.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: external-server-ca-cert
  namespace: composable-resource-operator-system
type: Opaque
stringData:
  ca.crt: |
{{- nindent 4 $.Values.global.fti_cdi.externalCA.certificate }}
