apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: composable-dra-secret
  namespace: composable-dra
stringData:
  username: {{ .Values.global.fti_cdi.credentials.username | quote }}
  password: {{ .Values.global.fti_cdi.credentials.password | quote }}
  realm: {{ .Values.global.fti_cdi.credentials.realm | quote }}
  client_id: {{ .Values.global.fti_cdi.credentials.client_id | quote }}
  client_secret: {{ .Values.global.fti_cdi.credentials.client_secret | quote }}
  certificate: |
{{- nindent 4 .Values.global.fti_cdi.externalCA.certificate }}
